name: pascal_modular
dependencies:
  - python=3.12
  - ipython
  - matplotlib
  - pandas
  - termcolor
  - matplotlib
  - numpy
  - scipy
  - netcdf4
  - ffmpeg
  - pyproj
  - libgdal
  - gdal
  - xarray
  - dask
  - cfgrib
  - cf_xarray
  - pygrib
  - xhistogram
  - requests
  - pytest<8
  - pytest-cov
  - pytest-benchmark
  - pytest-mpl
  - cartopy
  - nc-time-axis
  - geojson
  - pynucos>=2.12
  - isodate
  - coloredlogs
  - cmocean
  - utm
  - roaring-landmask>=0.7
  - traja
  - adios_db
  - pyyaml
  - pip
